name: NPM - Complete JS Utils

on:
  push:
    branches: ["main", "develop"]

jobs:
  unit-tests:
    name: Unit-Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - run: npm install --global yarn
      - run: yarn

      - name: Unit Tests (using Jest)
        run: yarn test

  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"
    strategy:
      matrix:
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install --global yarn
      - run: yarn
      - run: yarn install
      - run: yarn build
    # - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm install --global yarn
      - run: yarn
      - run: yarn install
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
